swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.1.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions :
    post:
        tags:
          - User Module
        summary: Transactions API
        description: API for fetching account transactions
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
            type: string
          - in: body
            name: body
            description: Account Payload
            required: true
            schema:
              $ref: '#/definitions/Transactions'
        produces:
          - application/json
        responses:
          '200':
            description: Account transactions retrieved Successfully
            schema:
              $ref: '#/definitions/TransactionsResponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /user/transactions/{id_transaction}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transactions API
      description: API for updating a transaction's category
      parameters:
        - in: path
          name: id_transaction
          description: transaction id
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionsCategoryUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/TransactionsUpdateCategoryResponse'
        '400':
          description: Invalid id
        '500':
          description: Internal Server Error
  /user/transactions/{id_transaction}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transactions API
      description: API for updating a transaction's notes
      parameters:
        - in: path
          name: id_transaction
          description: transaction id
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionsNotesUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/TransactionsUpdateNotesResponse'
        '400':
          description: Invalid id
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
      accountId:
        type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      transactions:
        type: object
        properties:
          transaction:
            type: object
            properties:
              id: 
                type: string
              date: 
                type: string
              description:
                type: string
              amount:
                type: number
              balance:
                type: number
              type:
                type: string
              category:
                type: string
              notes:
                type: string
  TransactionsCategoryUpdate:
    type: object
    properties:
      category:
        type: string
  TransactionsNotesUpdate:
    type: object
    properties:
      notes:
        type: string
  TransactionsUpdateCategoryResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          category:
            type: string
  TransactionsUpdateNotesResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          notes:
            type: string

